package ScriptHelper;

import org.dom4j.DocumentException;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import com.relevantcodes.extentreports.LogStatus;

import Driver.DriverHelper;
import Driver.Log;
import Driver.xmlreader;
import Reporter.ExtentTestManager;

public class SiebelOrderHelper extends DriverHelper{
	
	

	WebElement el;
	xmlreader xml=new xmlreader("src\\Locators\\SiebelOrder.xml");
	
	public SiebelOrderHelper(WebDriver parentdriver)
	{
		super(parentdriver);
	}
	public static String CircuitRefnumber;
//---------------------------------
	
	
	public void CreateSiebelOrder(Object[] Inputdata) throws Exception
	{
		Thread.sleep(10000);
//		Clickon(getwebelement(xml.getlocator("//locators/Accounts")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Accounts");
//		Clickon(getwebelement(xml.getlocator("//locators/AccountAdministration")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Account Administration");
//		Clickon(getwebelement(xml.getlocator("//locators/AccountsDropdown")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Account AccountsDropdown");
//		Clickon(getwebelement(xml.getlocator("//locators/SelectAccountNo")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Selecting Account No");
//		Thread.sleep(10000);
//		SendKeys(getwebelement(xml.getlocator("//locators/InputAccountNo")),Inputdata[3].toString());
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Account No");
//		Clickon(getwebelement(xml.getlocator("//locators/AccountGoButton")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on AccountGoButton");
//		Clickon(getwebelement(xml.getlocator("//locators/AccountName")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on AccountName");
//		SendKeys(getwebelement(xml.getlocator("//locators/OCNfield")),Inputdata[3].toString());
//        ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter OCN field");
//		Clickon(getwebelement(xml.getlocator("//locators/GoButton")));
//        ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on GoButton");
//		Clickon(getwebelement(xml.getlocator("//locators/AccountName")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on AccountName");
		Thread.sleep(30000);
		Clickon(getwebelement(xml.getlocator("//locators/InstalledAssetNew")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installed Asset New");
		SendKeys(getwebelement(xml.getlocator("//locators/OpportunityNo")),Inputdata[4].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Opportunity No");
		SendKeys(getwebelement(xml.getlocator("//locators/RequestReceivedDate")),Inputdata[5].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Request Received Date");
		SendKeys(getwebelement(xml.getlocator("//locators/DeliveryChannel")),Inputdata[6].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Delivery Channel");
		Clickon(getwebelement(xml.getlocator("//locators/OrderingPartySearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ordering Party Search");
		Clickon(getwebelement(xml.getlocator("//locators/PartySearchPopupDropdown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Party Search Popup Dropdown");
		Clickon(getwebelement(xml.getlocator("//locators/PartyName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Party Name");
		SendKeys(getwebelement(xml.getlocator("//locators/InputPartyname")),Inputdata[7].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Party Name");
		Clickon(getwebelement(xml.getlocator("//locators/PickAccntOk")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Account Ok");
		Clickon(getwebelement(xml.getlocator("//locators/OrderingPartyAddrSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Odering Party Address Search");
		Clickon(getwebelement(xml.getlocator("//locators/OrderingPartyAddrSearchDropdown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ordering Party Address Search Dropdown");
		Clickon(getwebelement(xml.getlocator("//locators/PartyAddr")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ordering Party Address");
		SendKeys(getwebelement(xml.getlocator("//locators/InputPartyAddr")),Inputdata[8].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Input Party Address");
		Clickon(getwebelement(xml.getlocator("//locators/PickAddrSubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Address Submit");
		Clickon(getwebelement(xml.getlocator("//locators/OrderingPartyContactSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ordering Party Contact Search");
		Clickon(getwebelement(xml.getlocator("//locators/PartyContactPopupDropdown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Party Contact Popup Dropdown");
		Clickon(getwebelement(xml.getlocator("//locators/FirstName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on First Name");
		SendKeys(getwebelement(xml.getlocator("//locators/InputFirstname")),Inputdata[9].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Input First Name");
		Clickon(getwebelement(xml.getlocator("//locators/FirstnameSubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on First Name Submit");
		SendKeys(getwebelement(xml.getlocator("//locators/SalesChannel")),Inputdata[10].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Sales Channel");
		Clickon(getwebelement(xml.getlocator("//locators/NewServiceOrder")));	
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on New Service Order");		
		Thread.sleep(30000);
		
	}
	
	public void AddEthernetLineSiteA(Object[] Inputdata) throws Exception
	{
		Clickon(getwebelement(xml.getlocator("//locators/AddEthernetLine")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Add Ethernet Line");
		Thread.sleep(10000);
		ServiceOrder = Gettext(getwebelement(xml.getlocator("//locators/ServiceOrderReferenceNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Generated Service Order Reference No: "+ServiceOrder);
		Log.info(ServiceOrder);
		Clickon(getwebelement(xml.getlocator("//locators/ServiceOrderReferenceNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Order Reference No");	
		Clickon(getwebelement(xml.getlocator("//locators/SearchAddressSiteA")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Address SiteA");	
		SendKeys(getwebelement(xml.getlocator("//locators/StreetName")),Inputdata[30].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Street Name");	
		SendKeys(getwebelement(xml.getlocator("//locators/Country")),Inputdata[31].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Country");	
		SendKeys(getwebelement(xml.getlocator("//locators/City")),Inputdata[32].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter City");	
		SendKeys(getwebelement(xml.getlocator("//locators/PostalCode")),Inputdata[33].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Postal Code");	
		SendKeys(getwebelement(xml.getlocator("//locators/Premises")),Inputdata[34].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Premises");
		Clickon(getwebelement(xml.getlocator("//locators/Search")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search");	
		Clickon(getwebelement(xml.getlocator("//locators/pickAddress")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Address");	
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement("//table[@id='address_table']//tr//td[contains(text(),'"+Inputdata[35].toString()+"')]"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Building");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement("//table[@id='address_table']//tr//td[contains(text(),'"+Inputdata[36].toString()+"')]"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Site");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/ServicePartySearchSiteA")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Party Search SiteA");
		Select(getwebelement(xml.getlocator("//locators/SelectServiceParty")),"Party Name");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Party");
		Thread.sleep(5000);
		SendKeys(getwebelement(xml.getlocator("//locators/InputServicePartyName")),Inputdata[19].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Service Party Name");
		Clickon(getwebelement(xml.getlocator("//locators/SearchServicePartyName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Service Party Name");
		Clickon(getwebelement(xml.getlocator("//locators/pickServiceParty")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Service Party");
		Clickon(getwebelement(xml.getlocator("//locators/PickButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Button");
		Clickon(getwebelement(xml.getlocator("//locators/SiteContactSearchSiteA")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Site Contact Search SiteA");
		SendKeys(getwebelement(xml.getlocator("//locators/InputContactName")),Inputdata[20].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/SearchContactName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/pickContactName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/PickContact")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact");
		Thread.sleep(10000);
	}
	
	public void AddEthernetLineSiteBAddress(Object[] Inputdata) throws Exception
	{
		Clickon(getwebelement(xml.getlocator("//locators/SearchAddressSiteB")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Address SiteB");
		SendKeys(getwebelement(xml.getlocator("//locators/StreetName")),Inputdata[47].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Street Name");
		SendKeys(getwebelement(xml.getlocator("//locators/Country")),Inputdata[48].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Country");
		SendKeys(getwebelement(xml.getlocator("//locators/City")),Inputdata[49].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter City");
		SendKeys(getwebelement(xml.getlocator("//locators/PostalCode")),Inputdata[50].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Postal Code");
		SendKeys(getwebelement(xml.getlocator("//locators/Premises")),Inputdata[51].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Premises");
		Clickon(getwebelement(xml.getlocator("//locators/Search")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search");
		Clickon(getwebelement(xml.getlocator("//locators/pickAddress")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Address");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement("//table[@id='address_table']//tr//td[contains(text(),'"+Inputdata[52].toString()+"')]"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Building");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement("//table[@id='address_table']//tr//td[contains(text(),'"+Inputdata[53].toString()+"')]"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Site");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/ServicePartySearchSiteB")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Party Search SiteB");
		Select(getwebelement(xml.getlocator("//locators/SelectServiceParty")),"Party Name");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Party");
		SendKeys(getwebelement(xml.getlocator("//locators/InputServicePartyName")),Inputdata[19].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Service Party Name");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/SearchServicePartyName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Service Party Name");
		Clickon(getwebelement(xml.getlocator("//locators/pickServiceParty")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Service Party");
		Clickon(getwebelement(xml.getlocator("//locators/PickButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Button");
		Clickon(getwebelement(xml.getlocator("//locators/SiteContactSearchSiteB")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Site Contact Search SiteB");
		Thread.sleep(10000);
		SendKeys(getwebelement(xml.getlocator("//locators/InputContactName")),Inputdata[20].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/SearchContactName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/pickContactName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/PickContact")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact");
		Thread.sleep(10000);
	}
	
	public void ASiteCustomize(Object[] Inputdata) throws Exception
	{
		Clickon(getwebelement(xml.getlocator("//locators/CustomizeButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Customize Button");
		Select(getwebelement(xml.getlocator("//locators/Coverage")),Inputdata[17].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Coverage");
		Thread.sleep(8000);
		Select(getwebelement(xml.getlocator("//locators/ServiceBandwidth")),Inputdata[18].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Bandwidth");
		Thread.sleep(8000);
		Select(getwebelement(xml.getlocator("//locators/AEndResilienceOption")),Inputdata[15].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select AEnd Resilience Option");
		Select(getwebelement(xml.getlocator("//locators/BEndResilienceOption")),Inputdata[16].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select BEnd Resilience Option");
//		savePage();
		Clickon(getwebelement(xml.getlocator("//locators/EthernetConnectionLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ethernet Connection Link");
		Clickon(getwebelement(xml.getlocator("//locators/AEndSite")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on AEnd Site");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Search");
		Clickon(getwebelement("//table[@summary='Select Access Technology']//tr//td[text()='"+Inputdata[63].toString()+"']"));
//		SendKeys(getwebelement(xml.getlocator("//locators/AccessTechnologyInput")),Inputdata[63].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Select");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Submit");
		Thread.sleep(5000);
		Select(getwebelement(xml.getlocator("//locators/CustomerSitePopStatus")),Inputdata[38].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Customer Site Pop Status");
		Thread.sleep(5000);
		Select(getwebelement(xml.getlocator("//locators/BuildingType")),Inputdata[37].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Building");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/CPEInformationLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on CPE Information Link");
		Select(getwebelement(xml.getlocator("//locators/CabinetType")),Inputdata[40].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Cabinet Type");
		Thread.sleep(10000);
		getwebelement(xml.getlocator("//locators/CabinetId")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Cabinet Id");
		SendKeys(getwebelement(xml.getlocator("//locators/CabinetId")),Inputdata[41].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Enter Cabinet Id");
		Clickon(getwebelement(xml.getlocator("//locators/ShelfID")));
		Thread.sleep(10000);
		safeJavaScriptClick(getwebelement(xml.getlocator("//locators/AccessPortLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Port Link");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/PresentationInterfaceSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Presentation Interface Search");
		Clickon(getwebelement("//table[@summary='Select Presentation Interface-Connector Type']//tr//td[text()='"+Inputdata[43].toString()+"']"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Select Presentation Interface");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitPresentationInterface")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Presentation Interface");
		Thread.sleep(10000);
		Select(getwebelement(xml.getlocator("//locators/PortRole")),Inputdata[42].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Port Role");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/AEndSite")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on A End Site");
		Clickon(getwebelement(xml.getlocator("//locators/InstallationTimeLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation Time Link");
		Select(getwebelement(xml.getlocator("//locators/InstallTime")),Inputdata[39].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Install Time");
		Clickon(getwebelement(xml.getlocator("//locators/EthernetConnectionLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ethernet Connection Link");
		}
	public void BSiteCustomize(Object[] Inputdata) throws Exception
	{
		Clickon(getwebelement(xml.getlocator("//locators/BEndSite")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on B End Site");
	//	Clickon(getwebelement(xml.getlocator("//locators/ThirdPartyAccessProviderSearch")));
	//	ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Third Party Access Provider Search");
	//	Clickon(getwebelement(xml.getlocator("//locators/ThirdPartyAccessProviderSelect")));
	//	ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Third Party Access Provider Select");
	//	Clickon(getwebelement(xml.getlocator("//locators/ThirdPartyAccessProviderSubmit")));
	//	ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Third Party Access Provider Submit");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Search");
		Clickon(getwebelement("//table[@summary='Select Access Technology']//tr//td[text()='"+Inputdata[64].toString()+"']"));
//		SendKeys(getwebelement(xml.getlocator("//locators/AccessTechnologyInput")),Inputdata[64].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Select");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Submit");
		Thread.sleep(5000);
		Select(getwebelement(xml.getlocator("//locators/CustomerSitePopStatusBEnd")),Inputdata[55].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Customer Site Pop Status B End");
		Thread.sleep(5000);
		Select(getwebelement(xml.getlocator("//locators/BuildingtypeBEnd")),Inputdata[54].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Building type BEnd");
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/CPEInformationLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on CPE Information Link");
		Select(getwebelement(xml.getlocator("//locators/CabinetTypeBEnd")),Inputdata[57].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Cabinet Type B End");
		getwebelement(xml.getlocator("//locators/CabinetIdBEnd")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Cabinet Id BEnd");
		SendKeys(getwebelement(xml.getlocator("//locators/CabinetIdBEnd")),Inputdata[58].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Cabinet Id BEnd");
		Clickon(getwebelement(xml.getlocator("//locators/ShelfID")));
		Thread.sleep(5000);
		safeJavaScriptClick(getwebelement(xml.getlocator("//locators/AccessPortLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Port Link");
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/PresentationInterfaceSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Presentation Interface Search");
		Clickon(getwebelement("//table[@summary='Select Presentation Interface-Connector Type']//tr//td[text()='"+Inputdata[60].toString()+"']"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Select Presentation Interface");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitPresentationInterface")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Presentation Interface");
		Thread.sleep(5000);
		Select(getwebelement(xml.getlocator("//locators/PortRoleBEnd")),Inputdata[59].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Port Role B End");
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/BEndSite")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on B End Site");
		Clickon(getwebelement(xml.getlocator("//locators/InstallationTimeLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation Time Link");
		Select(getwebelement(xml.getlocator("//locators/InstallTimeBEnd")),Inputdata[56].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Install Time BEnd");
		Clickon(getwebelement(xml.getlocator("//locators/DoneEthernetConnection")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Done Ethernet Connection");
	//	AcceptJavaScriptMethod();
		Thread.sleep(20000);
	}

	public void Workflow(Object[] Inputdata) throws Exception
	{
		Thread.sleep(20000);
		Clickon(getwebelement(xml.getlocator("//locators/OrderSubTypeSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Sub Type Search");
		Clickon(getwebelement(xml.getlocator("//locators/AddOrderSubType")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Add Order Sub Type");
		SendKeys(getwebelement(xml.getlocator("//locators/InputOrderSubType")),"New");
		SendkeaboardKeys(getwebelement(xml.getlocator("//locators/InputOrderSubType")),Keys.ENTER);
//		Clickon(getwebelement(xml.getlocator("//locators/OrderSubTypeDropDown")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Sub Type DropDown");
//		Clickon(getwebelement(xml.getlocator("//locators/SelectNew")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Select New");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitSubOrderType")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Sub Order Type");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/ContractSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Contract Search");
		Clickon(getwebelement("//table[@summary='Pick Contract']//tr//td[text()='"+Inputdata[12].toString()+"']"));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step:  Select Contract");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitContract")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Contract");
		Thread.sleep(3000);
		SendKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),Inputdata[14].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Existing Capacity Lead Time Primary");
		SendkeaboardKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),Keys.ENTER);
		SendkeaboardKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),Keys.TAB);
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/OrderDates")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Dates");
		Thread.sleep(3000);
		SendKeys(getwebelement(xml.getlocator("//locators/OrderSignedDate")),Inputdata[21].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Signed Date");
	    SendKeys(getwebelement(xml.getlocator("//locators/ColtActualDate")),Inputdata[23].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Colt Actual Date");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderReceivedDate")),Inputdata[22].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Received Date");
		Clickon(getwebelement(xml.getlocator("//locators/Billing")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Billing");
		Thread.sleep(3000);
		SendKeys(getwebelement(xml.getlocator("//locators/ContractTerm")),Inputdata[28].toString());
		Clickon(getwebelement(xml.getlocator("//locators/SelectContractTerm")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contract Term");
		Thread.sleep(10000);
		SendKeys(getwebelement(xml.getlocator("//locators/ContractRenewalFlag")),Inputdata[29].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contract Renewal Flag");
		SendkeaboardKeys(getwebelement(xml.getlocator("//locators/ContractRenewalFlag")),Keys.TAB);
		Thread.sleep(2000);
		Clickon(getwebelement(xml.getlocator("//locators/ExpandAllButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Expand All Button");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/InstallationChargeNRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation Charge NRC");
		getwebelement(xml.getlocator("//locators/InputinstallationChargeNRC")).clear();
		SendKeys(getwebelement(xml.getlocator("//locators/InputinstallationChargeNRC")),Inputdata[24].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Installation Charge NRC");
		Clickon(getwebelement(xml.getlocator("//locators/RecurringChargeMRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Recurring Charge MRC");
		getwebelement(xml.getlocator("//locators/InputRecurringChargeMRC")).clear();
		SendKeys(getwebelement(xml.getlocator("//locators/InputRecurringChargeMRC")),Inputdata[25].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Recurring Charge MRC");
		Clickon(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Installation Charge NRC");
		Thread.sleep(1000);
		Clickon(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRCSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Installation Charge NRC Search");
		SendKeys(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRCInput")),Inputdata[26].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter BCN Installation Charge NRC Input");
		Clickon(getwebelement(xml.getlocator("//locators/BCNNRCSubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN NRC Submit");
		Clickon(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Recurring Charge MRC");
		Thread.sleep(1000);
		Clickon(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRCSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Recurring Charge MRC Search");
		SendKeys(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRCInput")),Inputdata[27].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter BCN Recurring Charge MRC Input");
		Clickon(getwebelement(xml.getlocator("//locators/BCNNRCSubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN NRC Submit");
		Thread.sleep(5000);
//		Clickon(getwebelement(xml.getlocator("//locators/WarningOk")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click Ok in displayed Warning");
//		Thread.sleep(10000);
		getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Commercial Validation");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Entered Order Status Commercial Validation");
		SendkeaboardKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),Keys.ENTER);
		Thread.sleep(10000);
		SendkeaboardKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),Keys.TAB);		
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/OrderStatusDropdown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Entered Order Status Technical Validation");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/SelectTechnicalValidation")));
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/TriggerTRButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Trigger TR Button");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/OrderStatusDropdown")));
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/SelectDeliveryValidation")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Entered Order Status Delivery");
		Thread.sleep(10000);
		Select(getwebelement(xml.getlocator("//locators/OSSPlatformFlag")),"IQNet");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select OSS Platform Flag");
		Thread.sleep(20000);
//		savePage();
//		Clickon(getwebelement(xml.getlocator("//locators/WarningOk")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click Ok in displayed Warning");
//		Thread.sleep(40000);
		waitandForElementDisplay(("//locators/SubmitTechnicalOrder"),2);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Waiting for Submit Technical Order button");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitTechnicalOrder")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Technical Order");
		Thread.sleep(120000);
		waitandForElementDisplay(("//locators/CircuitReference"),2);
		CircuitRefnumber=GetInputValue(getwebelement(xml.getlocator("//locators/CircuitReference")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Generated Circuit Reference No: "+CircuitRefnumber);
		Log.info(CircuitRefnumber);
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/TechnicalOrderTab")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Technical Order Tab");
		TechnicalOrderStatus = Gettext(getwebelement(xml.getlocator("//locators/TechnicalOrderStatus")));
		VerifyText(TechnicalOrderStatus);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Verify Technical Order Status "+TechnicalOrderStatus);
		
	}

	public void AddProductEthernetHub(Object[] Inputdata) throws Exception{
			Clickon(getwebelement(xml.getlocator("//locators/AdddEthernetHub")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Addd Ethernet Hub");
			Thread.sleep(10000);
			ServiceOrder = Gettext(getwebelement(xml.getlocator("//locators/ServiceOrderReferenceNo")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Generated Service Order Reference No: "+ServiceOrder);
			Clickon(getwebelement(xml.getlocator("//locators/ServiceOrderReferenceNo")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Order Reference No");
			Clickon(getwebelement(xml.getlocator("//locators/Searchbutton")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Button");
			SendKeys(getwebelement(xml.getlocator("//locators/StreetName")),Inputdata[30].toString());
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Street Name");	
			SendKeys(getwebelement(xml.getlocator("//locators/Country")),Inputdata[31].toString());
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Country");	
			SendKeys(getwebelement(xml.getlocator("//locators/City")),Inputdata[32].toString());
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter City");	
			SendKeys(getwebelement(xml.getlocator("//locators/PostalCode")),Inputdata[33].toString());
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Postal Code");	
			SendKeys(getwebelement(xml.getlocator("//locators/Premises")),Inputdata[34].toString());
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Premises");	
			Clickon(getwebelement(xml.getlocator("//locators/Search")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search");	
			Clickon(getwebelement(xml.getlocator("//locators/pickAddress")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Address");	
			Clickon(getwebelement(xml.getlocator("//locators/Pick")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
			Clickon(getwebelement(xml.getlocator("//locators/pickBuilding")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Building");
			Clickon(getwebelement(xml.getlocator("//locators/Pick")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
			Clickon(getwebelement(xml.getlocator("//locators/PickSite")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Site");
			Clickon(getwebelement(xml.getlocator("//locators/Pick")));
			ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		   Clickon(getwebelement(xml.getlocator("locators/ServicePartySearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Party Search");
		   Select(getwebelement(xml.getlocator("//locators/SelectServiceParty")),"Party Name");
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Party Search");
		   SendKeys(getwebelement(xml.getlocator("//locators/InputServicePartyName")),Inputdata[19].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Service Party Name");
		   Clickon(getwebelement(xml.getlocator("//locators/SearchServicePartyName")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Party Name");
		   Clickon(getwebelement(xml.getlocator("//locators/pickServiceParty")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Party");
		   Clickon(getwebelement(xml.getlocator("//locators/PickButton")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Button");
		   Clickon(getwebelement(xml.getlocator("//locators/SiteContactSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Site Contact Search");
		   SendKeys(getwebelement(xml.getlocator("//locators/InputContactName")),Inputdata[20].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contact Name");
		   Clickon(getwebelement(xml.getlocator("//locators/SearchContactName")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Contact Name");
		   Clickon(getwebelement(xml.getlocator("//locators/pickContactName")));
		    ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact Name");
		   Clickon(getwebelement(xml.getlocator("//locators/PickContact")));
		    ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact");
		   Clickon(getwebelement(xml.getlocator("//locators/CustomizeButton")));
		    ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Customize Button");
		   Select(getwebelement(xml.getlocator("//locators/ServiceBandwidth")),Inputdata[18].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Bandwidth");
		   Thread.sleep(5000);
		   savePage();
		   Select(getwebelement(xml.getlocator("//locators/SelectResilienceOption")),Inputdata[15].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select ResilienceOption");
		   Clickon(getwebelement(xml.getlocator("//locators/EthernetConnectionLink")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ethernet Connection Link");
		   Clickon(getwebelement(xml.getlocator("//locators/HubSiteLink")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Hub Site Link");
		   Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Search");
		   Clickon(getwebelement(xml.getlocator("//locators/SelectAccessTechnology")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology");
		   Clickon(getwebelement(xml.getlocator("//locators/SubmitAccessTechnology")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Technology Search");
		   Thread.sleep(5000);
		   Select(getwebelement(xml.getlocator("//locators/CustomerSitePopStatus")),Inputdata[38].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Customer Site Pop Status");
		   Thread.sleep(5000);
		   Select(getwebelement(xml.getlocator("//locators/BuildingType")),Inputdata[37].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Building Type");
		   Clickon(getwebelement(xml.getlocator("//locators/CPEInformationLink")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on CPE Information Link");
		   Select(getwebelement(xml.getlocator("//locators/CabinetType")),Inputdata[40].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Cabinet Type");
		   getwebelement(xml.getlocator("//locators/CabinetId")).clear();
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Cabinet ID");
		   SendKeys(getwebelement(xml.getlocator("//locators/CabinetId")),Inputdata[41].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Cabinet ID");
		   Clickon(getwebelement(xml.getlocator("//locators/ShelfID")));
		   Thread.sleep(5000);
		   safeJavaScriptClick(getwebelement(xml.getlocator("//locators/AccessPortLink")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Port Link");
		   Clickon(getwebelement(xml.getlocator("//locators/PresentationInterfaceSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Presentation Interface Search");
		   Clickon(getwebelement(xml.getlocator("//locators/SelectPresentationInterfaceHub")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Presentation Interface Hub");
		   Clickon(getwebelement(xml.getlocator("//locators/SubmitPresentationInterface")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Presentation Interface");
		   Thread.sleep(5000);
		   Select(getwebelement(xml.getlocator("//locators/PortRole")),Inputdata[42].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Port Role");
		   Thread.sleep(5000);
		   Clickon(getwebelement(xml.getlocator("//locators/HubSiteLink")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Hub Site Link");
		   Clickon(getwebelement(xml.getlocator("//locators/InstallationTimeLink")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation Time Link");
		   Select(getwebelement(xml.getlocator("//locators/InstallTime")),Inputdata[39].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Install Time");
		   Clickon(getwebelement(xml.getlocator("//locators/DoneEthernetConnection")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ethernet Connection");
		   Thread.sleep(20000);
		   Clickon(getwebelement(xml.getlocator("//locators/OrderSubTypeSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Sub Type Search");
	   	   Clickon(getwebelement(xml.getlocator("//locators/AddOrderSubType")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Add Order Sub Type");
		   SendKeys(getwebelement(xml.getlocator("//locators/InputOrderSubType")),"New");
		   SendkeaboardKeys(getwebelement(xml.getlocator("//locators/InputOrderSubType")),Keys.ENTER);
	//	   Clickon(getwebelement(xml.getlocator("//locators/OrderSubTypeDropDown")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Sub Type DropDown");
	//	   Clickon(getwebelement(xml.getlocator("//locators/SelectNew")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Select New");
		   Clickon(getwebelement(xml.getlocator("//locators/SubmitSubOrderType")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Sub Order Type");
		   Thread.sleep(3000);
		   Clickon(getwebelement(xml.getlocator("//locators/ContractSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Contract Search");
		   Clickon(getwebelement(xml.getlocator("//locators/SubmitContract")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Contract");
		   Thread.sleep(3000);
		   Clickon(getwebelement(xml.getlocator("//locators/NetworkReferenceSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Network Reference Search");
		   Clickon(getwebelement(xml.getlocator("//locators/AddNetworkReferenceSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Add Network Reference Search");
		   Clickon(getwebelement(xml.getlocator("//locators/SubmitNetworkReference")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Network Reference");
		   Thread.sleep(3000);
		   NetworkReference = Gettext(getwebelement(xml.getlocator("//locators/NetworkReference")));
		   Log.info(NetworkReference);
		   getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		   SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Commercial Validation");
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		   Clickon(getwebelement(xml.getlocator("//locators/OrderDates")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Dates");
		   Thread.sleep(5000);
		   SendKeys(getwebelement(xml.getlocator("//locators/OrderSignedDate")),Inputdata[21].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Signed Date");
		   SendKeys(getwebelement(xml.getlocator("//locators/ColtActualDate")),Inputdata[23].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Colt Actual Date");
		   SendKeys(getwebelement(xml.getlocator("//locators/OrderReceivedDate")),Inputdata[22].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Received Date");
		   Clickon(getwebelement(xml.getlocator("//locators/Billing")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Billing");
		   Clickon(getwebelement(xml.getlocator("//locators/ExpandAllButton")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Expand All Button");
		   SendKeys(getwebelement(xml.getlocator("//locators/InstallationChargeNRC")),Inputdata[24].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Installation Charge NRC");
		   SendKeys(getwebelement(xml.getlocator("//locators/RecurringChargeMRC")),Inputdata[25].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Recurring Charge NRC");
		   Clickon(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRC")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Installation Charge NRC");
		   Clickon(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRCSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Installation Charge NRC Search");
		   SendKeys(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRCInput")),Inputdata[26].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter BCN Installation Charge NRC Input");
		   Clickon(getwebelement(xml.getlocator("//locators/BCNNRCSubmit")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN NRC Submit");
		   Clickon(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRC")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Recurring Charge MRC");
		   Clickon(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRCSearch")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Recurring Charge MRC Search");
		   SendKeys(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRCInput")),Inputdata[27].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter BCN Recurring Charge MRC Input");
		   Clickon(getwebelement(xml.getlocator("//locators/BCNNRCSubmit")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN NRC Submit");
		   SendKeys(getwebelement(xml.getlocator("//locators/ContractTerm")),Inputdata[28].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contract Term");
		   SendKeys(getwebelement(xml.getlocator("//locators/ContractRenewalFlag")),Inputdata[29].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contract Renewal Flag");
		   getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		   SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Technical validation");
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		   Clickon(getwebelement(xml.getlocator("//locators/TriggerTRButton")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Trigger TR Button");
		   SendKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),Inputdata[14].toString());
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Existing Capacity Lead Time Primary");
		   getwebelement(xml.getlocator("//locator/OrderStatus")).clear();
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		   SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Delivery");
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		   Select(getwebelement(xml.getlocator("//locators/OSSPlatformFlag")),"IQNet");
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select OSS Platform Flag");
		   Clickon(getwebelement(xml.getlocator("//locators/SubmitTechnicalOrder")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Technical Order");
		   Clickon(getwebelement(xml.getlocator("//locators/TechnicalOrderTab")));
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Technical Order Tab");
		   String TechnicalOrderStatus = Gettext(getwebelement(xml.getlocator("//locators/TechnicalOrderStatus")));
		   VerifyTextpresent(TechnicalOrderStatus);
		   ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Verify Technical Order Status ");
		   		
	}
	public void AddProductEthernetSpoke(Object[] Inputdata) throws Exception, DocumentException{
		Clickon(getwebelement(xml.getlocator("//locators/AddEthernetSpoke")));
		 ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Add Ethernet Spoke");
		Thread.sleep(10000);
		ServiceOrder = Gettext(getwebelement(xml.getlocator("//locators/ServiceOrderReferenceNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Generated Service Order Reference No: "+ServiceOrder);
		Clickon(getwebelement(xml.getlocator("//locators/ServiceOrderReferenceNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Order Reference No");
		Clickon(getwebelement(xml.getlocator("//locators/OrderSubTypeSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Sub Type Search");
		Clickon(getwebelement(xml.getlocator("//locators/AddOrderSubType")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Add Order Sub Type");
		Clickon(getwebelement(xml.getlocator("//locators/OrderSubTypeDropDown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Sub Type DropDown");
		Clickon(getwebelement(xml.getlocator("//locators/SelectNew")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Select New");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitSubOrderType")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Sub Order Type");
		Clickon(getwebelement(xml.getlocator("//locators/ContractSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Contract Search");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitContract")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Contract");
		Clickon(getwebelement(xml.getlocator("//locators/NetworkReferenceSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Network Reference Search");
		SendKeys(getwebelement(xml.getlocator("//locators/InputNetworkReference")),NetworkReference);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Input Network Reference");
		Clickon(getwebelement(xml.getlocator("//locators/SearchNetworkReference")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Network Reference");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitNetworkReference")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Network Reference");
		Select(getwebelement(xml.getlocator("//locators/CoverageSpoke")),Inputdata[17].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Coverage Spoke");
		Select(getwebelement(xml.getlocator("//locators/ResilienceSpoke")),Inputdata[15].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Resilience Spoke");
		Select(getwebelement(xml.getlocator("//locators/ServiceBandwidthSpoke")),Inputdata[18].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Bandwidth Spoke");
		
		
		
		Clickon(getwebelement(xml.getlocator("//locators/SearchAddressSiteB")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Address SiteB");
		SendKeys(getwebelement(xml.getlocator("//locators/StreetName")),Inputdata[47].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Street Name");
		SendKeys(getwebelement(xml.getlocator("//locators/Country")),Inputdata[48].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Country");
		SendKeys(getwebelement(xml.getlocator("//locators/City")),Inputdata[49].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter City");
		SendKeys(getwebelement(xml.getlocator("//locators/PostalCode")),Inputdata[50].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Postal Code");
		SendKeys(getwebelement(xml.getlocator("//locators/Premises")),Inputdata[51].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Premises");
		Clickon(getwebelement(xml.getlocator("//locators/Search")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search");
		Clickon(getwebelement(xml.getlocator("//locators/pickAddress")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Address");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement(xml.getlocator("//locators/pickBuilding")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Building");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement(xml.getlocator("//locators/PickSite")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Site");
		Clickon(getwebelement(xml.getlocator("//locators/Pick")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick");
		Clickon(getwebelement(xml.getlocator("//locators/ServicePartySearchSiteB")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Party Search SiteB");
		Select(getwebelement(xml.getlocator("//locators/SelectServiceParty")),"Party Name");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Party");
		SendKeys(getwebelement(xml.getlocator("//locators/InputServicePartyName")),Inputdata[19].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Service Party Name");
		Clickon(getwebelement(xml.getlocator("//locators/SearchServicePartyName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Service Party Name");
		Clickon(getwebelement(xml.getlocator("//locators/pickServiceParty")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Service Party");
		Clickon(getwebelement(xml.getlocator("//locators/PickButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Button");
		Clickon(getwebelement(xml.getlocator("//locators/SiteContactSearchSiteB")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Site Contact Search SiteB");
		SendKeys(getwebelement(xml.getlocator("//locators/InputContactName")),Inputdata[20].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/SearchContactName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/pickContactName")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact Name");
		Clickon(getwebelement(xml.getlocator("//locators/PickContact")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Pick Contact");
		Clickon(getwebelement(xml.getlocator("//locators/CustomizeButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Customize Button");
		Select(getwebelement(xml.getlocator("//locators/Coverage")),Inputdata[17].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Coverage");
		Select(getwebelement(xml.getlocator("//locators/ServiceBandwidth")), Inputdata[18].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Service Bandwidth");
		Select(getwebelement(xml.getlocator("//locators/Resilience")),Inputdata[15].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Resilience Option");
		Clickon(getwebelement(xml.getlocator("//locators/EthernetConnectionLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Ethernet Connection Link");
		Clickon(getwebelement(xml.getlocator("//locators/SpokeSiteLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Spoke Site Link");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Search");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySelect")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Select");
		Clickon(getwebelement(xml.getlocator("//locators/AccessTechnologySubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Technology Submit");
		Select(getwebelement(xml.getlocator("//locators/CustomerSitePopStatus")),Inputdata[38].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Customer Site Pop Status");
		Thread.sleep(5000);
		Select(getwebelement(xml.getlocator("//locators/BuildingType")),Inputdata[37].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Building");
		Thread.sleep(5000);
		Clickon(getwebelement(xml.getlocator("//locators/CPEInformationLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on CPE Information Link");
		Select(getwebelement(xml.getlocator("//locators/CabinetType")),Inputdata[40].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Cabinet Type");
		getwebelement(xml.getlocator("//locators/CabinetId")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Cabinet Id");
		SendKeys(getwebelement(xml.getlocator("//locators/CabinetId")),Inputdata[41].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Enter Cabinet Id");
		Thread.sleep(10000);
		safeJavaScriptClick(getwebelement(xml.getlocator("//locators/AccessPortLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Access Port Link");
		Clickon(getwebelement(xml.getlocator("//locators/PresentationInterfaceSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Presentation Interface Search");
		Clickon(getwebelement(xml.getlocator("//locators/SelectPresentationInterfaceSpoke")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Select Presentation Interface");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitPresentationInterface")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Presentation Interface");
		Select(getwebelement(xml.getlocator("//locators/PortRole")),Inputdata[42].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Port Role");
		Clickon(getwebelement(xml.getlocator("//locators/VLAN")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on VLAN link");
		SendKeys(getwebelement(xml.getlocator("//locators/VlanTagId")),Inputdata[45].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Vlan Tag Id");
		Clickon(getwebelement(xml.getlocator("//locators/SpokeSiteLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Spoke Site Link");
		Clickon(getwebelement(xml.getlocator("//locators/InstallationTimeLink")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation Time Link");
		Select(getwebelement(xml.getlocator("//locators/InstallTime")),Inputdata[39].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select Install Time");
		Clickon(getwebelement(xml.getlocator("//locators/DoneEthernetConnection")));
		getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Commercial Validation");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		Clickon(getwebelement(xml.getlocator("//locators/OrderDates")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order Dates");
		Thread.sleep(3000);
		SendKeys(getwebelement(xml.getlocator("//locators/OrderSignedDate")),Inputdata[21].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Signed Date");
	    SendKeys(getwebelement(xml.getlocator("//locators/ColtActualDate")),Inputdata[23].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Colt Actual Date");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderReceivedDate")),Inputdata[22].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Received Date");
		Clickon(getwebelement(xml.getlocator("//locators/Billing")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Billing");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/ExpandAllButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Expand All Button");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/InstallationChargeNRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation Charge NRC");
		SendKeys(getwebelement(xml.getlocator("//locators/InputinstallationChargeNRC")),Inputdata[24].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Installation Charge NRC");
		Clickon(getwebelement(xml.getlocator("//locators/RecurringChargeMRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Recurring Charge MRC");
		SendKeys(getwebelement(xml.getlocator("//locators/InputRecurringChargeMRC")),Inputdata[25].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Recurring Charge MRC");
		Clickon(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Installation Charge NRC");
		Thread.sleep(1000);
		Clickon(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRCSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Installation Charge NRC Search");
		SendKeys(getwebelement(xml.getlocator("//locators/BCNInstallationChargeNRCInput")),Inputdata[26].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter BCN Installation Charge NRC Input");
		Clickon(getwebelement(xml.getlocator("//locators/BCNNRCSubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN NRC Submit");
		Clickon(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRC")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Recurring Charge MRC");
		Thread.sleep(1000);
		Clickon(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRCSearch")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN Recurring Charge MRC Search");
		SendKeys(getwebelement(xml.getlocator("//locators/BCNRecurringChargeMRCInput")),Inputdata[27].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter BCN Recurring Charge MRC Input");
		Clickon(getwebelement(xml.getlocator("//locators/BCNNRCSubmit")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on BCN NRC Submit");
		SendKeys(getwebelement(xml.getlocator("//locators/ContractTerm")),Inputdata[28].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contract Term");
		SendKeys(getwebelement(xml.getlocator("//locators/ContractRenewalFlag")),Inputdata[29].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Contract Renewal Flag");
		getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Technical validation");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		Clickon(getwebelement(xml.getlocator("//locators/TriggerTRButton")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Trigger TR Button");
		SendKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),Inputdata[14].toString());
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Existing Capacity Lead Time Primary");
		getwebelement(xml.getlocator("//locator/OrderStatus")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Delivery");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		Select(getwebelement(xml.getlocator("//locators/OSSPlatformFlag")),"IQNet");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Select OSS Platform Flag");
		Clickon(getwebelement(xml.getlocator("//locators/SubmitTechnicalOrder")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Submit Technical Order");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/TechnicalOrderTab")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Technical Order Tab");
		String TechnicalOrderStatus = Gettext(getwebelement(xml.getlocator("//locators/TechnicalOrderStatus")));
		VerifyTextpresent(TechnicalOrderStatus);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Verify Technical Order Status ");
		
		
		
		
	}
	
	public void OrderCompleteEthernetLine() throws Exception, Exception
	{
		Clickon(getwebelement(xml.getlocator("//locators/ServiceOrderTab")));
		Thread.sleep(10000);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Order Tab");
		SendKeys(getwebelement(xml.getlocator("//locators/InputOrderNo")),ServiceOrder);
//		SendKeys(getwebelement(xml.getlocator("//locators/InputOrderNo")),"871324854/181215-0005");
		Thread.sleep(10000);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Input Order No");
		Clickon(getwebelement(xml.getlocator("//locators/SearchOrderNo")));
		Thread.sleep(10000);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Order No");
		Clickon(getwebelement(xml.getlocator("//locators/ClickOrderNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order No");
		Thread.sleep(30000);
		Clickon(getwebelement(xml.getlocator("//locators/DropDown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Drop down");
		Clickon(getwebelement(xml.getlocator("//locators/InstallationAndTestTab")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation And Test Tab");
		SendKeys(getwebelement(xml.getlocator("//locators/PrimaryTestingMethod")),"Not Required");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Primary Testing Method");
		getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
//		Clickon(getwebelement(xml.getlocator("//locators/WarningOk")));
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click Ok in displayed Warning");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/OrderStatusDropdown")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order status drop down");
		Thread.sleep(3000);
		Clickon(getwebelement(xml.getlocator("//locators/SelectCompleted")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click Completed Status");
		Thread.sleep(10000);
		Clickon(getwebelement(xml.getlocator("//locators/OrderComplete")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click Order Complete");
		Thread.sleep(20000);
//		SendKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),"No");
//		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Existing Capacity Lead Time Primary");
		
	}
	public void OrderCompleteEthernetHub() throws Exception, DocumentException{
		Clickon(getwebelement(xml.getlocator("//locators/ServiceOrderTab")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Service Order Tab");
		SendKeys(getwebelement(xml.getlocator("//locators/InputOrderNo")),ServiceOrder);
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Input Order No");
		Clickon(getwebelement(xml.getlocator("//locators/SearchOrderNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Search Order No");
		Clickon(getwebelement(xml.getlocator("//locators/ClickOrderNo")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Order No");
		Clickon(getwebelement(xml.getlocator("//locators/InstallationAndTestTab")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click on Installation And Test Tab");
		SendKeys(getwebelement(xml.getlocator("//locators/PrimaryTestingMethod")),"Not Required");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Primary Testing Method");
		getwebelement(xml.getlocator("//locators/OrderStatus")).clear();
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Clear Order Status");
		SendKeys(getwebelement(xml.getlocator("//locators/OrderStatus")),"Completed");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Order Status");
		Clickon(getwebelement(xml.getlocator("//locators/OrderComplete")));
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Click Order Complete");
		SendKeys(getwebelement(xml.getlocator("//locators/ExistingCapacityLeadTimePrimary")),"No");
		ExtentTestManager.getTest().log(LogStatus.PASS, " Step: Enter Existing Capacity Lead Time Primary");
		
	}
//	private void SendKeys(WebElement el, Object object) {
//		
//		el.sendKeys((CharSequence[]) object);
//	}	
//	
	
}
